[package]
name = "wasmer-tests/wasmer-edge-dashy-sample"
version = "0.1.0"
description = "Dashy dashboard running on EdgeJS on Wasmer Edge"

[dependencies]
"wasmer/edgejs-quickjs" = "0.0.8"

[fs]
"/app" = "./app/edge-build"

[[command]]
name = "server"
module = "wasmer/edgejs-quickjs:edge"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["/app/server/index.cjs"]
cwd = "/app"
env = ["HOST=0.0.0.0", "NODE_ENV=production", "HOME=/tmp"]
