[package]
name = "wasmer-tests/wasmer-edge-next-ssr-sample"
version = "0.1.0"
description = "Next.js SSR (standalone output) running on EdgeJS on Wasmer Edge"

[dependencies]
"wasmer/edgejs-quickjs" = "0.0.8"

[fs]
"/app" = ".next/standalone"

[[command]]
name = "server"
module = "wasmer/edgejs-quickjs:edge"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["/app/server.js"]
env = ["HOSTNAME=0.0.0.0", "NODE_ENV=production", "HOME=/tmp"]
