// Compile Etherpad's TypeScript backend to plain CommonJS JavaScript ahead of
// time, on native Node, so the server can be run with a plain `node` (and thus
// by EdgeJS/QuickJS, which does not strip TypeScript at runtime).
//
// Upstream Etherpad runs its `.ts` sources directly via `tsx` (esbuild at
// runtime). EdgeJS can only execute final built artifacts, so here we do the
// exact same transformation esbuild/tsx would do, but ahead of time: every
// `src/**/*.ts` is transpiled in place to a sibling `.js`. In-place output is
// required because the backend uses path-relative requires such as
// `require("../../../static/...")` that must resolve against the real src tree.
//
// Side effects, both consumed by the framework-test harness:
//   * a `.cache/` marker dir so the harness treats the build as a reusable
//     generated artifact and does NOT try to rebuild under EdgeJS on the edge
//     stages (it only ever builds on native Node);
//   * a managed block in `.gitignore` listing every emitted `.js` so the
//     compiled output never gets committed.

import { createRequire } from 'node:module';
import { readdirSync, writeFileSync, readFileSync, mkdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
// esbuild is a dependency of the ep_etherpad-lite (src) workspace, not the root.
const require = createRequire(path.join(root, 'src', 'package.json'));
const esbuild = require('esbuild');

const srcDir = path.join(root, 'src');

function collectTsFiles(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === 'tests') continue;
      out.push(...collectTsFiles(full));
    } else if (entry.name.endsWith('.ts') && !entry.name.endsWith('.d.ts')) {
      out.push(full);
    }
  }
  return out;
}

const tsFiles = collectTsFiles(srcDir);
if (tsFiles.length === 0) {
  console.error('build-backend: no .ts files found under src/');
  process.exit(1);
}

await esbuild.build({
  entryPoints: tsFiles,
  outdir: srcDir,
  outbase: srcDir,
  format: 'cjs',
  platform: 'node',
  target: 'node24',
  logLevel: 'error',
  sourcemap: false,
});

const emitted = tsFiles
  .map((f) => path.relative(root, f).replace(/\.ts$/, '.js'))
  .sort();

// Reuse marker for the framework-test harness (see file header).
mkdirSync(path.join(root, '.cache'), { recursive: true });
writeFileSync(
  path.join(root, '.cache', 'backend-build.json'),
  JSON.stringify({ files: emitted.length }, null, 2) + '\n',
);

// Keep compiled output out of git via a managed .gitignore block.
const START = '# >>> compiled-backend (generated by build-backend.mjs)';
const END = '# <<< compiled-backend';
const gitignorePath = path.join(root, '.gitignore');
let current = existsSync(gitignorePath) ? readFileSync(gitignorePath, 'utf8') : '';
const before = current.split(START)[0].replace(/\s*$/, '\n');
const block = [START, '/.cache/', ...emitted.map((f) => `/${f}`), END, ''].join('\n');
writeFileSync(gitignorePath, `${before}${block}`);

console.log(`build-backend: transpiled ${emitted.length} TypeScript files to CommonJS`);
