// @ts-nocheck
'use strict';

/**
 * This code is mostly from the old Etherpad. Please help us to comment this code.
 * This helps other people to understand this code better and helps them to improve it.
 * TL;DR COMMENTS ON THIS FILE ARE HIGHLY APPRECIATED
 */

// DO NOT EDIT THIS FILE, edit infrastructure/ace/www/colorutils.js
// THIS FILE IS ALSO SERVED AS CLIENT-SIDE JS
/**
 * Copyright 2009 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS-IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const colorutils = {};

// Check that a given value is a css hex color value, e.g.
// "#ffffff" or "#fff"
colorutils.isCssHex = (cssColor) => /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(cssColor);

// "#ffffff" or "#fff" or "ffffff" or "fff" to [1.0, 1.0, 1.0]
colorutils.css2triple = (cssColor) => {
  const sixHex = colorutils.css2sixhex(cssColor);

  const hexToFloat = (hh) => Number(`0x${hh}`) / 255;
  return [
    hexToFloat(sixHex.substr(0, 2)),
    hexToFloat(sixHex.substr(2, 2)),
    hexToFloat(sixHex.substr(4, 2)),
  ];
};

// "#ffffff" or "#fff" or "ffffff" or "fff" to "ffffff"
colorutils.css2sixhex = (cssColor) => {
  let h = /[0-9a-fA-F]+/.exec(cssColor)[0];
  if (h.length !== 6) {
    const a = h.charAt(0);
    const b = h.charAt(1);
    const c = h.charAt(2);
    h = a + a + b + b + c + c;
  }
  return h;
};

// [1.0, 1.0, 1.0] -> "#ffffff"
colorutils.triple2css = (triple) => {
  const floatToHex = (n) => {
    const n2 = colorutils.clamp(Math.round(n * 255), 0, 255);
    return (`0${n2.toString(16)}`).slice(-2);
  };
  return `#${floatToHex(triple[0])}${floatToHex(triple[1])}${floatToHex(triple[2])}`;
};


colorutils.clamp = (v, bot, top) => v < bot ? bot : (v > top ? top : v);
colorutils.min3 = (a, b, c) => (a < b) ? (a < c ? a : c) : (b < c ? b : c);
colorutils.max3 = (a, b, c) => (a > b) ? (a > c ? a : c) : (b > c ? b : c);
colorutils.colorMin = (c) => colorutils.min3(c[0], c[1], c[2]);
colorutils.colorMax = (c) => colorutils.max3(c[0], c[1], c[2]);
colorutils.scale = (v, bot, top) => colorutils.clamp(bot + v * (top - bot), 0, 1);
colorutils.unscale = (v, bot, top) => colorutils.clamp((v - bot) / (top - bot), 0, 1);

colorutils.scaleColor = (c, bot, top) => [
  colorutils.scale(c[0], bot, top),
  colorutils.scale(c[1], bot, top),
  colorutils.scale(c[2], bot, top),
];

colorutils.unscaleColor = (c, bot, top) => [
  colorutils.unscale(c[0], bot, top),
  colorutils.unscale(c[1], bot, top),
  colorutils.unscale(c[2], bot, top),
];

// rule of thumb for RGB brightness; 1.0 is white
colorutils.luminosity = (c) => c[0] * 0.30 + c[1] * 0.59 + c[2] * 0.11;

colorutils.saturate = (c) => {
  const min = colorutils.colorMin(c);
  const max = colorutils.colorMax(c);
  if (max - min <= 0) return [1.0, 1.0, 1.0];
  return colorutils.unscaleColor(c, min, max);
};

colorutils.blend = (c1, c2, t) => [
  colorutils.scale(t, c1[0], c2[0]),
  colorutils.scale(t, c1[1], c2[1]),
  colorutils.scale(t, c1[2], c2[2]),
];

colorutils.invert = (c) => [1 - c[0], 1 - c[1], 1 - c[2]];

colorutils.complementary = (c) => {
  const inv = colorutils.invert(c);
  return [
    (inv[0] >= c[0]) ? Math.min(inv[0] * 1.30, 1) : (c[0] * 0.30),
    (inv[1] >= c[1]) ? Math.min(inv[1] * 1.59, 1) : (c[1] * 0.59),
    (inv[2] >= c[2]) ? Math.min(inv[2] * 1.11, 1) : (c[2] * 0.11),
  ];
};

// --- WCAG 2.1 helpers (issue #7377) ------------------------------------------
// Pre-fix text colour selection used `luminosity(bg) < 0.5` as the cutoff,
// which produced WCAG-AA-failing combinations for mid-saturation author
// colours (e.g. pure red #ff0000 paired with white text gives a 4.0 contrast
// ratio — below the 4.5 threshold and genuinely hard to read). The helpers
// below implement WCAG 2.1 relative luminance and contrast ratio so text
// colour selection can pick the higher-contrast option and always clear AA.
//
// Reference: https://www.w3.org/TR/WCAG21/#dfn-relative-luminance
colorutils.relativeLuminance = (c) => {
  const toLinear = (v) => v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
  return 0.2126 * toLinear(c[0]) + 0.7152 * toLinear(c[1]) + 0.0722 * toLinear(c[2]);
};

// WCAG 2.1 contrast ratio between two sRGB triples, in [1, 21]. 4.5 = AA
// for body text; 7.0 = AAA.
colorutils.contrastRatio = (c1, c2) => {
  const l1 = colorutils.relativeLuminance(c1);
  const l2 = colorutils.relativeLuminance(c2);
  return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);
};

// Per-skin rendered text colours for WCAG comparisons (issue #7377). The
// `*Ref` values are the colours actually painted in the browser — they MUST
// match what the CSS variables resolve to so contrast comparisons reflect
// what the user sees. The `*Out` values are what we hand back to CSS (the
// variable name in colibris, a hex literal otherwise).
//
// Colibris dark = #485365 from src/static/skins/colibris/pad.css's
// --super-dark-color. If that variable is ever retuned, update this table.
const SKIN_TEXT_COLORS = {
  colibris: {darkRef: '#485365', lightRef: '#ffffff', darkOut: 'var(--super-dark-color)', lightOut: 'var(--super-light-color)'},
  default: {darkRef: '#222222', lightRef: '#ffffff', darkOut: '#222', lightOut: '#fff'},
};
const skinTextColors = (skinName) => SKIN_TEXT_COLORS[skinName] || SKIN_TEXT_COLORS.default;

// WCAG-aware text-colour selection (issue #7377). Pick whichever of the two
// rendered text colours for the active skin produces the higher contrast
// ratio against the background.
colorutils.textColorFromBackgroundColor = (bgcolor, skinName) => {
  const refs = skinTextColors(skinName);
  const triple = colorutils.css2triple(bgcolor);
  const ratioDark = colorutils.contrastRatio(triple, colorutils.css2triple(refs.darkRef));
  const ratioLight = colorutils.contrastRatio(triple, colorutils.css2triple(refs.lightRef));
  return ratioDark >= ratioLight ? refs.darkOut : refs.lightOut;
};

// Some backgrounds (the issue's #9AB3FA, every mid-saturation primary like
// #ff0000) cannot meet AA against either rendered text colour for a given
// skin — text-colour selection alone can't fix them. ensureReadableBackground
// blends the bg toward the extreme OPPOSITE the better-contrast text in 5%
// increments until AA is met, preserving hue. Author's stored colour is
// untouched — this is a viewer-side render clamp.
//
// Returns the input unchanged for non-hex inputs (CSS vars etc.) so callers
// can apply this generically without first checking the value shape.
colorutils.ensureReadableBackground = (cssColor, skinName, minContrast) => {
  if (!colorutils.isCssHex(cssColor)) return cssColor;
  if (minContrast == null) minContrast = 4.5;
  const refs = skinTextColors(skinName);
  const dark = colorutils.css2triple(refs.darkRef);
  const light = colorutils.css2triple(refs.lightRef);
  const triple = colorutils.css2triple(cssColor);
  const ratioDark = colorutils.contrastRatio(triple, dark);
  const ratioLight = colorutils.contrastRatio(triple, light);
  if (Math.max(ratioDark, ratioLight) >= minContrast) return cssColor;
  // Better text colour wins; blend bg toward the opposite end so the
  // contrast against that text grows.
  const blendTarget = ratioDark >= ratioLight ? [1, 1, 1] : [0, 0, 0];
  const textRef = ratioDark >= ratioLight ? dark : light;
  for (let i = 1; i <= 20; i++) {
    const blended = colorutils.blend(triple, blendTarget, i * 0.05);
    if (colorutils.contrastRatio(blended, textRef) >= minContrast) {
      return colorutils.triple2css(blended);
    }
  }
  return colorutils.triple2css(blendTarget);
};

exports.colorutils = colorutils;
