<template>
  <main>
    <h1>Nuxt Static Example</h1>
    <p>Generated by Nuxt and served as static files by Wasmer Edge.</p>
  </main>
</template>

<style>
main {
  font-family: system-ui, sans-serif;
  margin: 4rem auto;
  max-width: 42rem;
  padding: 0 1rem;
}
</style>
