[package]
name = "wasmer-tests/wasmer-edge-totaljs-cms-sample"
version = "0.1.1"
description = "Total.js v5 CMS (filesystem database) running on EdgeJS on Wasmer Edge"

[dependencies]
"wasmer/edgejs-quickjs" = "0.0.8"

[fs]
"/app" = "./app"
"/etc" = "./etc"

[[command]]
name = "server"
module = "wasmer/edgejs-quickjs:edge"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["/app/index.js", "--release"]
cwd = "/app"
env = ["NODE_ENV=production", "HOME=/tmp"]
